[project]
name = "ibm-sp-mcp-server"
version = "0.1.0"
description = "MCP Server for IBM Storage Protect"
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.0.0",
    "python-dotenv>=1.0.0"
]

[project.scripts]
sp-mcp-server = "sp_mcp_server.main:main"
mcp-server-clients-core = "sp_mcp_server.main_clients_core:main"
mcp-server-clients-config = "sp_mcp_server.main_clients_config:main"
mcp-server-storage-pools = "sp_mcp_server.main_storage_pools:main"
mcp-server-storage-hardware = "sp_mcp_server.main_storage_hardware:main"
mcp-server-storage-device = "sp_mcp_server.main_storage_device:main"
mcp-server-policies-lifecycle = "sp_mcp_server.main_policies_lifecycle:main"
mcp-server-policies-management = "sp_mcp_server.main_policies_management:main"
mcp-server-system-admin = "sp_mcp_server.main_system_admin:main"
mcp-server-system-config = "sp_mcp_server.main_system_config:main"
mcp-server-ops-protection = "sp_mcp_server.main_ops_protection:main"
mcp-server-ops-maintenance = "sp_mcp_server.main_ops_maintenance:main"
mcp-server-ops-rules = "sp_mcp_server.main_ops_rules:main"

[project.optional-dependencies]
test = [
  "pytest",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/sp_mcp_server"]
